name: front_ia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_tts: ^4.2.2
  go_router: ^15.1.1
  grouped_list: ^6.0.0
  http: ^1.3.0
  intl: ^0.20.2
  lottie: ^3.3.1
  path: ^1.9.1
  riverpod: ^2.6.1
  speech_to_text: ^7.0.0
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/voice.json